# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1B1B1E)
$foreground = rgb(E4DBE3)
$color0 = rgb(424245)
$color1 = rgb(13141D)
$color2 = rgb(1A1A24)
$color3 = rgb(424453)
$color4 = rgb(4C4351)
$color5 = rgb(776677)
$color6 = rgb(857184)
$color7 = rgb(D0C3CF)
$color8 = rgb(918891)
$color9 = rgb(191B27)
$color10 = rgb(232330)
$color11 = rgb(585B6F)
$color12 = rgb(65596C)
$color13 = rgb(9F889F)
$color14 = rgb(B297B0)
$color15 = rgb(D0C3CF)
